"""Shared combination dictionary for Elemental Nexus."""
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Iterable


BASE_ELEMENTS: tuple[str, ...] = (
    'Fire',
    'Water',
    'Earth',
    'Air',
)

AGES: tuple[str, ...] = (
    'Primal',
    'Natural',
    'Civilization',
    'Industrial',
    'Modern',
    'Futuristic',
)


@dataclass(frozen=True)
class Combo:
    result: str
    ingredients: tuple[str, str]
    age: str


_COMBO_DATA: tuple[Combo, ...] = (
    Combo('Steam', ('Fire', 'Water'), 'Primal'),
    Combo('Lava', ('Earth', 'Fire'), 'Primal'),
    Combo('Smoke', ('Air', 'Fire'), 'Primal'),
    Combo('Mud', ('Earth', 'Water'), 'Primal'),
    Combo('Mist', ('Air', 'Water'), 'Primal'),
    Combo('Dust', ('Air', 'Earth'), 'Primal'),
    Combo('Plasma', ('Fire', 'Fire'), 'Primal'),
    Combo('Lake', ('Water', 'Water'), 'Primal'),
    Combo('Stone', ('Earth', 'Earth'), 'Primal'),
    Combo('Pressure', ('Air', 'Air'), 'Primal'),
    Combo('Metal', ('Fire', 'Stone'), 'Primal'),
    Combo('Crystal', ('Pressure', 'Water'), 'Primal'),
    Combo('Volcano', ('Earth', 'Lava'), 'Primal'),
    Combo('Geyser', ('Earth', 'Steam'), 'Primal'),
    Combo('Sand', ('Air', 'Stone'), 'Primal'),
    Combo('Swamp', ('Mist', 'Mud'), 'Primal'),
    Combo('Life', ('Energy', 'Swamp'), 'Primal'),
    Combo('Energy', ('Air', 'Plasma'), 'Primal'),
    Combo('Obsidian', ('Lava', 'Water'), 'Primal'),
    Combo('Ash', ('Earth', 'Smoke'), 'Primal'),
    Combo('Seed', ('Earth', 'Life'), 'Natural'),
    Combo('Tree', ('Seed', 'Water'), 'Natural'),
    Combo('Moss', ('Life', 'Stone'), 'Natural'),
    Combo('Fungus', ('Life', 'Swamp'), 'Natural'),
    Combo('Beast', ('Life', 'Tree'), 'Natural'),
    Combo('Bird', ('Air', 'Life'), 'Natural'),
    Combo('Fish', ('Life', 'Water'), 'Natural'),
    Combo('Reptile', ('Lava', 'Life'), 'Natural'),
    Combo('Herb', ('Mist', 'Seed'), 'Natural'),
    Combo('Flower', ('Energy', 'Tree'), 'Natural'),
    Combo('Forest', ('Tree', 'Tree'), 'Natural'),
    Combo('Bees', ('Air', 'Flower'), 'Natural'),
    Combo('Honey', ('Bees', 'Flower'), 'Natural'),
    Combo('Wolf', ('Beast', 'Forest'), 'Natural'),
    Combo('Human', ('Energy', 'Life'), 'Natural'),
    Combo('Tool', ('Human', 'Stone'), 'Civilization'),
    Combo('House', ('Tool', 'Tree'), 'Civilization'),
    Combo('Farm', ('Herb', 'Human'), 'Civilization'),
    Combo('Bread', ('Farm', 'Fire'), 'Civilization'),
    Combo('Cloth', ('Fungus', 'Tool'), 'Civilization'),
    Combo('Boat', ('Water', 'Wood'), 'Civilization'),
    Combo('Wood', ('Tool', 'Tree'), 'Civilization'),
    Combo('Wheel', ('Stone', 'Tool'), 'Civilization'),
    Combo('Cart', ('Wheel', 'Wood'), 'Civilization'),
    Combo('Road', ('Cart', 'Stone'), 'Civilization'),
    Combo('Market', ('Human', 'Road'), 'Civilization'),
    Combo('Currency', ('Market', 'Metal'), 'Civilization'),
    Combo('Writing', ('Human', 'Tool'), 'Civilization'),
    Combo('Library', ('House', 'Writing'), 'Civilization'),
    Combo('School', ('Human', 'Library'), 'Civilization'),
    Combo('Philosophy', ('Energy', 'Human'), 'Civilization'),
    Combo('Medicine', ('Herb', 'Human'), 'Civilization'),
    Combo('Music', ('Bird', 'Human'), 'Civilization'),
    Combo('Painting', ('Flower', 'Human'), 'Civilization'),
    Combo('Statue', ('Stone', 'Tool'), 'Civilization'),
    Combo('Castle', ('House', 'Stone'), 'Civilization'),
    Combo('Sail', ('Cloth', 'Wind'), 'Civilization'),
    Combo('Wind', ('Air', 'Energy'), 'Natural'),
    Combo('Navigation', ('Boat', 'Star'), 'Civilization'),
    Combo('Star', ('Air', 'Energy'), 'Primal'),
    Combo('Compass', ('Metal', 'Navigation'), 'Civilization'),
    Combo('Paper', ('Water', 'Wood'), 'Civilization'),
    Combo('Ink', ('Ash', 'Water'), 'Civilization'),
    Combo('Book', ('Ink', 'Paper'), 'Civilization'),
    Combo('PrintingPress', ('Book', 'Metal'), 'Industrial'),
    Combo('Coal', ('Pressure', 'Swamp'), 'Industrial'),
    Combo('SteamEngine', ('Metal', 'Steam'), 'Industrial'),
    Combo('Train', ('Cart', 'SteamEngine'), 'Industrial'),
    Combo('Factory', ('House', 'SteamEngine'), 'Industrial'),
    Combo('Electricity', ('Energy', 'Metal'), 'Industrial'),
    Combo('Battery', ('Electricity', 'Metal'), 'Industrial'),
    Combo('Lightbulb', ('Electricity', 'Glass'), 'Industrial'),
    Combo('Glass', ('Fire', 'Sand'), 'Industrial'),
    Combo('Concrete', ('Sand', 'Stone'), 'Industrial'),
    Combo('Oil', ('Pressure', 'Swamp'), 'Industrial'),
    Combo('Plastic', ('Energy', 'Oil'), 'Industrial'),
    Combo('Chemical', ('Oil', 'Water'), 'Industrial'),
    Combo('Radio', ('Air', 'Electricity'), 'Modern'),
    Combo('Television', ('Lightbulb', 'Radio'), 'Modern'),
    Combo('Computer', ('Electricity', 'Logic'), 'Modern'),
    Combo('Logic', ('Philosophy', 'Tool'), 'Civilization'),
    Combo('Circuit', ('Metal', 'Plastic'), 'Modern'),
    Combo('Robot', ('Computer', 'Metal'), 'Futuristic'),
    Combo('Drone', ('Air', 'Robot'), 'Futuristic'),
    Combo('Satellite', ('Radio', 'Rocket'), 'Futuristic'),
    Combo('Rocket', ('Fuel', 'Metal'), 'Modern'),
    Combo('Fuel', ('Fire', 'Oil'), 'Industrial'),
    Combo('Astronaut', ('Human', 'Rocket'), 'Modern'),
    Combo('SpaceStation', ('House', 'Satellite'), 'Futuristic'),
    Combo('AI', ('Computer', 'Logic'), 'Futuristic'),
    Combo('Nanotech', ('AI', 'Chemical'), 'Futuristic'),
    Combo('Fusion', ('Metal', 'Plasma'), 'Futuristic'),
    Combo('Hovercar', ('Nanotech', 'Vehicle'), 'Futuristic'),
    Combo('Vehicle', ('Cart', 'Engine'), 'Industrial'),
    Combo('Engine', ('Fuel', 'Metal'), 'Industrial'),
    Combo('City', ('House', 'Road'), 'Civilization'),
    Combo('Suburb', ('Garden', 'City'), 'Modern'),
    Combo('Garden', ('Flower', 'Tree'), 'Natural'),
    Combo('Skyscraper', ('City', 'Concrete'), 'Modern'),
    Combo('Internet', ('Computer', 'Radio'), 'Modern'),
    Combo('Smartphone', ('Computer', 'Television'), 'Modern'),
    Combo('App', ('Logic', 'Smartphone'), 'Modern'),
    Combo('Cloud', ('Internet', 'Mist'), 'Modern'),
    Combo('Server', ('Computer', 'Metal'), 'Modern'),
    Combo('DroneDelivery', ('Drone', 'Market'), 'Futuristic'),
    Combo('Biotech', ('Medicine', 'Nanotech'), 'Futuristic'),
    Combo('Terraformer', ('Earth', 'Nanotech'), 'Futuristic'),
    Combo('TimeCrystal', ('Crystal', 'Fusion'), 'Futuristic'),
    Combo('QuantumComputer', ('AI', 'Crystal'), 'Futuristic'),
    Combo('Hologram', ('AI', 'Lightbulb'), 'Futuristic'),
    Combo('Antigravity', ('Fusion', 'Wind'), 'Futuristic'),
    Combo('ForceField', ('Antigravity', 'Crystal'), 'Futuristic'),
    Combo('Singularity', ('AI', 'Fusion'), 'Futuristic'),
    Combo('EnergyGrid', ('City', 'Electricity'), 'Modern'),
    Combo('SolarPanel', ('Metal', 'Sun'), 'Modern'),
    Combo('Sun', ('Fire', 'Star'), 'Natural'),
    Combo('WindTurbine', ('Metal', 'Wind'), 'Modern'),
    Combo('HydroPlant', ('Electricity', 'Water'), 'Modern'),
    Combo('Dam', ('Concrete', 'River'), 'Industrial'),
    Combo('River', ('Lake', 'Pressure'), 'Natural'),
    Combo('Bridge', ('River', 'Stone'), 'Civilization'),
    Combo('Aqueduct', ('Bridge', 'Water'), 'Civilization'),
    Combo('Irrigation', ('Aqueduct', 'Farm'), 'Civilization'),
    Combo('MedicineHerb', ('Herb', 'Knowledge'), 'Civilization'),
    Combo('Knowledge', ('Book', 'School'), 'Civilization'),
    Combo('University', ('Philosophy', 'School'), 'Civilization'),
    Combo('Engineer', ('Tool', 'University'), 'Industrial'),
    Combo('Scientist', ('Energy', 'University'), 'Industrial'),
    Combo('Lab', ('Chemical', 'Scientist'), 'Industrial'),
    Combo('Research', ('Knowledge', 'Lab'), 'Modern'),
    Combo('Antibiotic', ('Lab', 'Medicine'), 'Modern'),
    Combo('Vaccine', ('Lab', 'Virus'), 'Modern'),
    Combo('Virus', ('Life', 'Swamp'), 'Natural'),
    Combo('Hospital', ('House', 'Medicine'), 'Modern'),
    Combo('PowerPlant', ('EnergyGrid', 'Fuel'), 'Modern'),
    Combo('Recycling', ('City', 'Plastic'), 'Modern'),
    Combo('Biodome', ('Forest', 'Terraformer'), 'Futuristic'),
    Combo('Mech', ('Engine', 'Robot'), 'Futuristic'),
    Combo('NeuralLink', ('AI', 'Human'), 'Futuristic'),
    Combo('Colony', ('SpaceStation', 'Terraformer'), 'Futuristic'),
    Combo('ChronoLab', ('Lab', 'TimeCrystal'), 'Futuristic'),
    Combo('StasisPod', ('ChronoLab', 'Hospital'), 'Futuristic'),
    Combo('DimensionalGate', ('ForceField', 'Singularity'), 'Futuristic'),
    Combo('Arcology', ('Biodome', 'Skyscraper'), 'Futuristic'),
    Combo('EcoCity', ('Arcology', 'Recycling'), 'Futuristic'),
    Combo('Starship', ('Fusion', 'Rocket'), 'Futuristic'),
    Combo('GalacticMap', ('Navigation', 'Starship'), 'Futuristic'),
    Combo('Chronicle', ('Book', 'TimeCrystal'), 'Futuristic'),
    Combo('Myth', ('Chronicle', 'Philosophy'), 'Futuristic'),
    Combo('Legacy', ('Chronicle', 'Knowledge'), 'Futuristic'),
    Combo('CosmicGarden', ('Biodome', 'Star'), 'Futuristic'),
    Combo('ElementalCore', ('Crystal', 'Fusion'), 'Futuristic'),
    Combo('Hypernet', ('Internet', 'QuantumComputer'), 'Futuristic'),
    Combo('GenesisSeed', ('ElementalCore', 'Life'), 'Futuristic'),
    Combo('SingularityEngine', ('Engine', 'Singularity'), 'Futuristic'),
    Combo('ChronoCompass', ('ChronoLab', 'Compass'), 'Futuristic'),
    Combo('LuminousInk', ('Ink', 'Lightbulb'), 'Modern'),
    Combo('NeonDye', ('Chemical', 'Lightbulb'), 'Modern'),
    Combo('Festival', ('City', 'Music'), 'Civilization'),
    Combo('Opera', ('House', 'Music'), 'Civilization'),
    Combo('Cuisine', ('Farm', 'Fire'), 'Civilization'),
    Combo('Spice', ('Fire', 'Herb'), 'Natural'),
    Combo('Tea', ('Herb', 'Water'), 'Natural'),
    Combo('Ceremony', ('Philosophy', 'Tea'), 'Civilization'),
    Combo('Guild', ('Knowledge', 'Market'), 'Civilization'),
    Combo('Bank', ('Currency', 'House'), 'Civilization'),
    Combo('Law', ('City', 'Philosophy'), 'Civilization'),
    Combo('Democracy', ('Human', 'Law'), 'Civilization'),
    Combo('Code', ('Law', 'Writing'), 'Civilization'),
    Combo('Constitution', ('Code', 'Democracy'), 'Civilization'),
    Combo('Parliament', ('Democracy', 'House'), 'Civilization'),
    Combo('Observation', ('Star', 'Tool'), 'Civilization'),
    Combo('Telescope', ('Glass', 'Observation'), 'Civilization'),
    Combo('Observatory', ('House', 'Telescope'), 'Civilization'),
    Combo('Calendar', ('Sun', 'Writing'), 'Civilization'),
    Combo('FestivalLights', ('Festival', 'Lightbulb'), 'Modern'),
)


def combos() -> Iterable[Combo]:
    """Return the tuple of all defined combinations."""
    return _COMBO_DATA


@lru_cache(maxsize=None)
def combo_lookup() -> dict[tuple[str, str], Combo]:
    lookup: dict[tuple[str, str], Combo] = {}
    for combo in _COMBO_DATA:
        key = tuple(sorted(combo.ingredients))
        lookup[key] = combo
    return lookup
