# Generated by ChatGPT on demand
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('discovered', models.JSONField(default=list)),
                ('energy', models.IntegerField(default=20)),
                ('legacy_multiplier', models.FloatField(default=1.0)),
                ('current_age_index', models.IntegerField(default=0)),
                ('last_energy_tick', models.DateTimeField(default=django.utils.timezone.now)),
                ('discovery_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game State',
                'verbose_name_plural': 'Game States',
            },
        ),
    ]
